.gitignore, src/main/kotlin/org/ton/intellij/tolk/ide/linemarker/FuncRecursiveCallLineMarkerProvider.kt
1. Fixed `.gitignore`. For some reason, it had the wrong path to autogen. https://github.com/ton-blockchain/intellij-ton/blob/92221bbfa14a3c7122e1cd0016acb2d36300dcd8/build.gradle.kts#L155
2. Removed unnecessary dependencies that make it impossible to build locally. After looking at the decompiled code via `fernflower`, I realized that it is `TolkSpecialApplyExpression` that is not referenced.
Please, do a squash during merge
=> fixed local build

src/main/kotlin/org/ton/intellij/tolk/refactor/FuncNamesValidator.kt
Previously, it was not checked that the new value was an identifier. This caused the PSI tree to be built incorrectly and resulted in an **NPE**
Now the IDE will prevent this from happening:
=> fixed name validation when refactoring

src/main/kotlin/org/ton/intellij/tolk/type/ty/Ty.kt
=> added support for the `void` type

modules/tolk/src/org/ton/intellij/tolk/codeInsight/hint/TolkParameterHintsProvider.kt
=> fix(tolk/inlay-hints): show `foo:` instead of `foo = `

modules/tolk/src/org/ton/intellij/tolk/codeInsight/hint/TolkParameterHintsProvider.kt
=> fix(tolk/inlay-hints): don't show parameter hints for single letter parameters

modules/tolk/src/org/ton/intellij/tolk/codeInsight/hint/TolkParameterHintsProvider.kt, modules/tolk/src/org/ton/intellij/tolk/psi/impl/TolkCallExpressionMixin.kt
=> fix(tolk/inlay-hints): don't show parameter hints for `ton()`

modules/tolk/src/org/ton/intellij/tolk/codeInsight/hint/TolkParameterHintsProvider.kt
=> feat(tolk/inlay-hints): don't show parameter hints for same name field access and function/method call

modules/tolk/resources/META-INF/tolk.xml
=> feat(tolk/inlay-hints): enable constant type hint by default

modules/fift/resources/META-INF/fift.xml, modules/fift/src/org/ton/intellij/fift/ide/FiftDumbAnnotator.kt, modules/fift/src/org/ton/intellij/fift/ide/documentation/DocumentationUtils.kt, modules/fift/src/org/ton/intellij/fift/ide/documentation/FiftDocumentationProvider.kt, modules/fift/src/org/ton/intellij/fift/ide/hints/FiftAssemblyInfoHintsProvider.kt, modules/fift/src/org/ton/intellij/fift/psi/elements.kt, modules/util/src/org/ton/intellij/util/asm/Data.kt
=> feat(fift/documentation): add hover documentation for instructions

modules/func/resources/META-INF/func.xml, modules/func/resources/colorSchemes/FuncDark.xml, modules/func/resources/colorSchemes/FuncDefault.xml, modules/func/src/org/ton/intellij/func/highlighting/FuncAnnotator.kt
=> feat(func/highlighting): better highlighting for method calls

modules/fift/src/org/ton/intellij/fift/parser/FiftParser.bnf
=> feat(fift): support interpreter sessions `[ ... ]` in Fift

modules/tolk/src/org/ton/intellij/tolk/doc/MarkdownNode.kt, modules/tolk/src/org/ton/intellij/tolk/doc/TolkDocumentationProvider.kt, modules/tolk/src/org/ton/intellij/tolk/doc/TolkDocumentationUtils.kt
=> feat(tolk/documentation): resolve element links like `[param]` in rendered doc

modules/tolk/src/org/ton/intellij/tolk/inspection/TolkTypeMismatchInspection.kt, modules/tolk/src/org/ton/intellij/tolk/psi/impl/TolkFunctionImpl.kt, modules/tolk/test/codeInsight/TolkCodeInsightTest.kt, modules/tolk/testResources/org.ton.intellij.tolk/tests/inference-tests.tolk, modules/tolk/testResources/org.ton.intellij.tolk/tests/never-return-functions.tolk
=> fix(tolk/type-inference): correctly infer `never` return type for function that always throws

modules/tolk/src/org/ton/intellij/tolk/psi/reference/TolkFieldLookupReference.kt
=> fix(tolk/resolving): fallback to resolve by any methods only if the receiver has an unknown type

modules/func/resources/META-INF/func.xml, modules/func/resources/inspectionDescriptions/FuncMissingImpure.html, modules/func/resources/messages/FuncBundle.properties, modules/func/src/org/ton/intellij/func/inspection/style/FuncMissingImpureInspection.kt, modules/func/src/org/ton/intellij/func/psi/FuncPsiFactory.kt
=> feat(func/inspections): warn about function with `()` return type and without `impure` modifier

modules/tolk/src/org/ton/intellij/tolk/ide/completion/TolkReturnCompletionProvider.kt, modules/tolk/test/completion/TolkCompletionTest.kt
=> feat(tolk/completion): add `return <expr>;` completion item for functions without an explicit return type

modules/tolk/src/org/ton/intellij/tolk/doc/TolkDocumentationProvider.kt, modules/tolk/src/org/ton/intellij/tolk/parser/TolkParser.bnf, modules/tolk/test/completion/TolkCompletionTest.kt, modules/tolk/testResources/documentation/enums.expected.html, modules/tolk/testResources/documentation/enums.tolk
=> feat(tolk): support enum serialization `enum Foo: uint8 {}`

modules/tolk/src/org/ton/intellij/tolk/doc/TolkDocumentationProvider.kt, modules/tolk/src/org/ton/intellij/tolk/ide/completion/TolkCompletionContributor.kt, modules/tolk/src/org/ton/intellij/tolk/ide/completion/TolkKeywordCompletionProvider.kt, modules/tolk/src/org/ton/intellij/tolk/ide/completion/TolkStructFieldModifierCompletionProvider.kt, modules/tolk/src/org/ton/intellij/tolk/lexer/TolkLexer.flex, modules/tolk/src/org/ton/intellij/tolk/parser/TolkParser.bnf, modules/tolk/src/org/ton/intellij/tolk/psi/TolkTokenType.kt, modules/tolk/src/org/ton/intellij/tolk/psi/impl/TolkStructFieldMixin.kt, modules/tolk/test/completion/TolkStructFieldModifierCompletionTest.kt, modules/tolk/testResources/documentation/struct.expected.html, modules/tolk/testResources/documentation/struct.tolk
=> feat(tolk): initial support for `readonly` and `private` modifiers

modules/tolk/src/org/ton/intellij/tolk/psi/reference/TolkMatchArmReference.kt, modules/tolk/test/resolving/TolkResolveMatchPatternTest.kt
=> fix(tolk/resolving): resolve a match pattern first to type and if unresolved — to other symbols

modules/tolk/src/org/ton/intellij/tolk/ide/completion/TolkDotExpressionCompletionProvider.kt
=> fix(tolk/completion): don't gray out method completion if qualifier is unresolved

modules/tolk/src/org/ton/intellij/tolk/ide/completion/TolkCommonCompletionProvider.kt, modules/tolk/src/org/ton/intellij/tolk/ide/completion/TolkTypeCompletionProvider.kt
=> fix(tolk/completion): don't add duplicate completion variant for primitive types in Tolk 1.1

modules/tolk/src/org/ton/intellij/tolk/ide/completion/TolkTopLevelSnippetsCompletionProvider.kt
=> fix(tolk/completion): don't add completion after `tolk 1<caret>`
