ton-blockchain/intellij-ton

src/main/kotlin/org/ton/intellij/tolk/ide/formatter/FuncFormatter.kt

most changes are related to the space before `)`

corrected rules in the formatting builder

---

modules/boc/build.gradle.kts
modules/boc/resources/META-INF/boc.xml
modules/boc/src/org/ton/intellij/boc/BocFileEditorProvider.kt

added feature to open .boc files (disassembled bytecode) in IDEA using ton-disassembler project https://github.com/espritoxyz/ton-disassembler

added .boc file disassembler

---

gradle.properties
modules/tolk/src/org/ton/intellij/tolk/ide/completion/TolkCompletionContributor.kt
modules/tolk/test/completion/TolkCompletionTest.kt
modules/util/build.gradle.kts

feat: add `lazy` keyword completion

---

modules/func/src/org/ton/intellij/func/ide/hints/FuncParameterHintsProvider.kt

feat(func/inlay-hints): don't show parameter hints for the same name function/method call and single letter parameters

---

modules/tolk/src/org/ton/intellij/tolk/ide/completion/TolkCompletionContributor.kt
modules/tolk/src/org/ton/intellij/tolk/ide/completion/TolkLookupElement.kt
modules/tolk/src/org/ton/intellij/tolk/ide/completion/TolkReturnCompletionProvider.kt
modules/tolk/src/org/ton/intellij/tolk/type/TolkIntTy.kt
modules/tolk/src/org/ton/intellij/tolk/type/TolkTy.kt
modules/tolk/test/completion/TolkCompletionTest.kt

feat(tolk/completion): better context return keyword completion

---

modules/tolk/src/org/ton/intellij/tolk/ide/completion/TolkAnnotationCompletionProvider.kt
modules/tolk/test/completion/TolkCompletionTest.kt

feat(tolk/completion): add string argument for @deprecated annotation completion

---

modules/func/resources/META-INF/func.xml
modules/func/src/org/ton/intellij/func/structure/FuncStructureViewFactory.kt

feat(func/ide): add structure view

---

modules/tolk/src/org/ton/intellij/tolk/ide/structure/TolkBreadcrumbsProvider.kt

feat(tolk/ide): improve breadcrumbs, fix spacing, add method receiver name and self if any

---

modules/func/resources/META-INF/func.xml
modules/func/resources/messages/FuncBundle.properties
modules/func/src/org/ton/intellij/func/ide/hints/FuncMethodIdHintsProvider.kt
modules/func/src/org/ton/intellij/func/psi/impl/FuncFunctionImpl.kt

feat(func/inlay-hints): add inlay hint for `method_id`

---

modules/func/src/org/ton/intellij/func/psi/impl/FuncReference.kt

If a symbol cannot be resolved in imported files, check all files in the current directory
Fixes #294

feat(func/resolving): improve resolving logic 

---

modules/tolk/resources/META-INF/tolk.xml
modules/tolk/src/org/ton/intellij/tolk/highlighting/TolkCheckAnnotator.kt
modules/tolk/src/org/ton/intellij/tolk/highlighting/checkers/TolkCheckerBase.kt
modules/tolk/src/org/ton/intellij/tolk/highlighting/checkers/TolkCommonProblemsChecker.kt
modules/tolk/src/org/ton/intellij/tolk/psi/impl/TolkBinExpressionMixin.kt

feat(tolk/inspections): add check for reassign immutable variable or constant

---

modules/tolk/src/org/ton/intellij/tolk/psi/TolkPsiFactory.kt
modules/tolk/src/org/ton/intellij/tolk/refactor/TolkNamesValidator.kt

feat(tolk/rename): automatically wrap to backticks on rename to non-identifier name

---

modules/tlb/resources/META-INF/tlb.xml
modules/tlb/src/org/ton/intellij/tlb/structure/TlbBreadcrumbsInfoProvider.kt

feat(tlb/ide): add breadcrumbs

---

modules/tolk/src/org/ton/intellij/tolk/ide/completion/TolkAnnotationCompletionProvider.kt
modules/tolk/test/completion/TolkCompletionTest.kt

feat(tolk/completion): add completion for `@on_bounced_policy` annotation

---

modules/tolk/src/org/ton/intellij/tolk/ide/completion/TolkAllMatchTypesCompletionProvider.kt
modules/tolk/src/org/ton/intellij/tolk/ide/completion/TolkCompletionContributor.kt
modules/tolk/test/completion/TolkCompletionTest.kt

Fixes #313
https://github.com/user-attachments/assets/e2ce2bd0-d555-4c7f-99e1-a346ee89f269

feat(tolk/completion): add completion variant to fill all match arms

---

modules/fift/resources/META-INF/fift.xml
modules/fift/src/org/ton/intellij/fift/FiftIcons.kt
modules/fift/src/org/ton/intellij/fift/ide/structure/FiftStructureViewFactory.kt
modules/fift/src/org/ton/intellij/fift/psi/FiftFile.kt

feat(fift/ide): add structure view for assembly

---

modules/tolk/resources/META-INF/tolk.xml
modules/tolk/src/org/ton/intellij/tolk/ide/TolkStringAsmInjector.kt

feat(tolk/asm): add injection of assembly language for Tolk assembly functions

---

modules/tolk/src/org/ton/intellij/tolk/psi/impl/TolkNamedElementImpl.kt

feat(tolk/ide): show type of struct field in the structure view

---

modules/func/src/org/ton/intellij/func/structure/FuncStructureViewFactory.kt

feat(func/structure-view): show includes in structure view

---

modules/tlb/resources/META-INF/tlb.xml
modules/tlb/src/org/ton/intellij/tlb/ide/actions/TlbCreateFileAction.kt

feat(tlb/actions): add new TL-B file action

---

modules/tolk/resources/META-INF/tolk.xml
modules/tolk/resources/inspectionDescriptions/TolkUnresolvedReference.html
modules/tolk/resources/messages/TolkBundle.properties
modules/tolk/src/org/ton/intellij/tolk/ide/imports/SelectionAwareListCellRenderer.kt
modules/tolk/src/org/ton/intellij/tolk/ide/imports/TolkImportFileQuickFix.kt
modules/tolk/src/org/ton/intellij/tolk/inspection/TolkUnresolvedReferenceInspection.kt
modules/tolk/src/org/ton/intellij/tolk/stub/index/TolkNamedElementIndex.kt

To import a file with possible definition
Fixes #240
https://github.com/user-attachments/assets/c83193c2-122a-45df-b343-4c83eb3b646e

feat(tolk/inspections): add a quickfix for unresolved references

---

modules/tolk/src/org/ton/intellij/tolk/psi/TolkFile.kt
modules/tolk/src/org/ton/intellij/tolk/psi/TolkPsiFactory.kt

fix(tolk/completion): fix auto-import insertion for files without imports

---

modules/tolk/src/org/ton/intellij/tolk/ide/completion/TolkExpressionFieldProvider.kt

feat(tolk/completion): add a default field value on field completion inside a struct instance

---

modules/tolk/resources/colorSchemes/TolkDark.xml
modules/tolk/resources/colorSchemes/TolkDefault.xml
modules/tolk/resources/colorSchemes/TolkHighlighterDemo.tolk
modules/tolk/resources/messages/TolkBundle.properties
modules/tolk/src/org/ton/intellij/tolk/highlighting/TolkDumbAnnotator.kt
modules/tolk/src/org/ton/intellij/tolk/ide/colors/TolkColor.kt

feat(tolk/highlighting): add special highlighting for mutable parameters and mutable self parameters

---

modules/tolk/src/org/ton/intellij/tolk/highlighting/TolkAnnotator.kt
modules/tolk/src/org/ton/intellij/tolk/lexer/TolkLexer.flex
modules/tolk/src/org/ton/intellij/tolk/parser/TolkParser.bnf
modules/tolk/src/org/ton/intellij/tolk/presentation/TolkPsiRenderer.kt
modules/tolk/src/org/ton/intellij/tolk/psi/TolkTokenType.kt
modules/tolk/src/org/ton/intellij/tolk/psi/impl/TolkVoidTypeExpressionMixin.kt

feat(tolk/grammar): support `type int = builtin`

---

modules/tolk/resources/META-INF/tolk.xml
modules/tolk/src/org/ton/intellij/tolk/ide/TolkAttachTestConsoleFiltersAtStartup.kt

feat(tolk/highlighting): highlight Tolk paths in Blueprint test output

---

modules/tolk/src/org/ton/intellij/tolk/ide/completion/TolkCompletionContributor.kt
modules/tolk/src/org/ton/intellij/tolk/ide/completion/TolkStorageSnippetCompletionProvider.kt
modules/tolk/test/completion/TolkCompletionTest.kt

fix(tolk/completion): add `storage` snippet

---

modules/tolk/src/org/ton/intellij/tolk/ide/completion/TolkCompletionContributor.kt
modules/tolk/src/org/ton/intellij/tolk/ide/completion/TolkFunctionNameCompletionProvider.kt
modules/tolk/test/completion/TolkCompletionTest.kt

feat(tolk/completion): add completion for entry point functions like `onInternalMessage` and special methods `unpackFromSlice` and `packToBuilder`

---

modules/tlb/resources/META-INF/tlb.xml
modules/tlb/src/org/ton/intellij/tlb/ide/completion/TlbCompletionContributor.kt
modules/tlb/src/org/ton/intellij/tlb/ide/completion/TlbCompletionProvider.kt
modules/tlb/src/org/ton/intellij/tlb/ide/completion/providers/TolkBuiltinTypesCompletionProvider.kt

feat(tlb/completion): add completion for builtin TL-B types

---

modules/tlb/src/org/ton/intellij/tlb/ide/completion/TlbCompletionContributor.kt
modules/tlb/src/org/ton/intellij/tlb/ide/completion/providers/TolkTypesCompletionProvider.kt
modules/tlb/src/org/ton/intellij/tlb/psi/TlbFile.kt

feat(tlb/completion): add completion for types

---

modules/tolk/src/org/ton/intellij/tolk/ide/fixes/TolkCreateConstantQuickfix.kt
modules/tolk/src/org/ton/intellij/tolk/ide/fixes/TolkCreateFunctionQuickfix.kt
modules/tolk/src/org/ton/intellij/tolk/ide/fixes/TolkCreateGlobalVariableQuickfix.kt
modules/tolk/src/org/ton/intellij/tolk/ide/fixes/TolkCreateLocalVariableQuickfix.kt
modules/tolk/src/org/ton/intellij/tolk/ide/fixes/TolkCreateTopLevelDeclarationQuickfix.kt
modules/tolk/src/org/ton/intellij/tolk/inspection/TolkUnresolvedReferenceInspection.kt
modules/tolk/test/quickfix/TolkCreateConstantQuickfixTest.kt
modules/tolk/test/quickfix/TolkCreateFunctionQuickfix.kt
modules/tolk/test/quickfix/TolkCreateGlobalVariableQuickfixTest.kt
modules/tolk/test/quickfix/TolkCreateLocalVariableQuickfixTest.kt
modules/tolk/test/quickfix/TolkQuickfixTestBase.kt

feat(tolk/inspections): add quickfix to create function, constant, global or local variable for unresolved identifier

---

modules/tolk/resources/META-INF/tolk.xml
modules/tolk/resources/inspectionDescriptions/TolkCallArgumentsCountMismatch.html
modules/tolk/src/org/ton/intellij/tolk/highlighting/TolkAnnotator.kt
modules/tolk/src/org/ton/intellij/tolk/inspection/TolkCallArgumentsCountMismatchInspection.kt
modules/tolk/test/inspection/TolkCallArgumentsCountMismatchInspectionTest.kt
modules/tolk/test/inspection/TolkInspectionTestBase.kt

feat(tolk/inspections): add `CallArgumentsCountMismatch` inspection

---

modules/tolk/src/org/ton/intellij/tolk/doc/TolkAnnotationInfo.kt
modules/tolk/src/org/ton/intellij/tolk/doc/TolkDocumentationProvider.kt
modules/tolk/testResources/documentation/annotations.expected.html
modules/tolk/testResources/documentation/annotations.tolk
modules/tolk/testResources/documentation/function.expected.html

feat(tolk/documentation): add documentation for annotations

---

modules/tolk/src/org/ton/intellij/tolk/ide/completion/LookupElements.kt
modules/tolk/src/org/ton/intellij/tolk/psi/TolkNamedElement.kt
modules/tolk/src/org/ton/intellij/tolk/psi/impl/TolkCatchParameterMixin.kt
modules/tolk/src/org/ton/intellij/tolk/psi/impl/TolkNamedElementImpl.kt
modules/tolk/src/org/ton/intellij/tolk/psi/impl/TolkSelfParameterMixin.kt
modules/tolk/src/org/ton/intellij/tolk/psi/impl/TolkVarMixin.kt
modules/tolk/test/completion/TolkCompletionTest.kt

fix(tolk/completion): fix backticked declarations completion

---

modules/func/src/org/ton/intellij/func/psi/impl/FuncReference.kt
modules/func/src/org/ton/intellij/func/resolve/FuncGlobalLookup.kt
modules/func/src/org/ton/intellij/func/type/infer/FuncTypeInferenceWalker.kt
modules/func/src/org/ton/intellij/func/type/infer/TypeInference.kt

fix(func/resolving): fix variables and methods resolving

---

modules/tlb/src/org/ton/intellij/tlb/ide/annotation.kt

feat(tlb/highlighting): highlight implicit TL-B field types

---

modules/tlb/src/org/ton/intellij/tlb/psi/TlbFile.kt
modules/tlb/src/org/ton/intellij/tlb/psi/TlbReference.kt

feat(tlb): add support for dependson include

---

modules/func/resources/META-INF/func.xml
modules/func/src/org/ton/intellij/func/ide/formatter/FuncCodeStyleSettings.kt
modules/func/src/org/ton/intellij/func/ide/formatter/FuncCodeStyleSettingsProvider.kt
modules/func/src/org/ton/intellij/func/ide/formatter/FuncLanguageCodeStyleSettingsProvider.kt

feat(func): add indent settings

---

modules/fift/src/org/ton/intellij/fift/lexer/FiftLexer.flex
modules/fift/src/org/ton/intellij/fift/parser/FiftParser.bnf

fix(fift): fix several parser errors in standart Fift files

---

modules/boc/build.gradle.kts
modules/boc/src/org/ton/intellij/boc/BocBase64Panel.kt
modules/boc/src/org/ton/intellij/boc/BocBasePanel.kt
modules/boc/src/org/ton/intellij/boc/BocCellTreePanel.kt
modules/boc/src/org/ton/intellij/boc/BocDisassemblyPanel.kt
modules/boc/src/org/ton/intellij/boc/BocHexPanel.kt

feat(boc): integrate TASM support to BoC viewer

---

modules/tolk/resources/META-INF/tolk.xml
modules/tolk/resources/inspectionDescriptions/TolkUnusedImport.html
modules/tolk/resources/messages/TolkBundle.properties
modules/tolk/src/org/ton/intellij/tolk/codeInsight/imports/TolkImportOptimizer.kt
modules/tolk/src/org/ton/intellij/tolk/inspection/TolkUnusedImportInspection.kt
modules/tolk/test/inspection/inspection/TolkUnusedImportInspectionTest.kt

feat(tolk/inspections): add unused import inspection and 'Optimize imports' action

---

modules/tolk/src/org/ton/intellij/tolk/ide/completion/TolkCompletionContributor.kt

feat(tolk/completion): add enum keyword completion

---

modules/tolk/src/org/ton/intellij/tolk/ide/imports/TolkImportFileQuickFix.kt

fix(tolk/intentions): don't try to import non top-level declarations

---

modules/tolk/src/org/ton/intellij/tolk/inspection/TolkUnresolvedReferenceInspection.kt

fix(tolk/inspections): don't suggest creating a local variable outside function

---

modules/func/resources/META-INF/func.xml
modules/func/resources/inspectionDescriptions/FuncOperatorPrecedence.html
modules/func/resources/messages/FuncBundle.properties
modules/func/src/org/ton/intellij/func/inspection/style/FuncOperatorPrecedenceInspection.kt

feat(func/inspections): warn about suspicious operator precedence in complex expressions

---

modules/tolk/src/org/ton/intellij/tolk/ide/completion/LookupElements.kt
modules/tolk/src/org/ton/intellij/tolk/ide/completion/TolkCommonCompletionProvider.kt
modules/tolk/test/completion/TolkEnumMemberCompletionTest.kt
modules/tolk/test/completion/TolkMatchCompletionTest.kt

feat(tolk/completion): add enum members completion without qualifier

---

modules/func/src/org/ton/intellij/func/ide/completion/FuncCommonCompletionProvider.kt

feat(func): better method completion

---

modules/func/src/org/ton/intellij/func/ide/fixes/FuncCreateFunctionQuickfix.kt
modules/func/src/org/ton/intellij/func/ide/fixes/FuncCreateTopLevelDeclarationQuickfix.kt
modules/func/src/org/ton/intellij/func/inspection/FuncUnresolvedReferenceInspection.kt

feat(func/inspections): add a quickfix to create an undefined function

---

modules/func/src/org/ton/intellij/func/ide/fixes/RenameUnserscoreFix.kt
modules/func/src/org/ton/intellij/func/inspection/FuncUnusedVariableInspection.kt

feat(func/inspections): support quickfix to rename unused variable to `_` for variables inside tensor like ``(int a, int b) = ...`

---

build.gradle.kts
modules/func/src/org/ton/intellij/func/eval/FuncValue.kt
modules/func/src/org/ton/intellij/func/inspection/FuncTypeMismatchInspection.kt
modules/func/src/org/ton/intellij/func/type/infer/FuncTypeInferenceWalker.kt
modules/func/src/org/ton/intellij/func/type/ty/Ty.kt
test/FuncJUnit4TestRunner.kt
test/FuncTestBase.kt
test/inspection/FuncInspectionTestBase.kt
test/inspection/FuncTypeMismatchInspectionTest.kt

feat(func/inspections): add full fledget type mismatch inspection

---

modules/tolk/test/codeInsight/TolkCodeInsightTest.kt
modules/tolk/test/codeInsight/codeInsight/TolkProjectsCodeInsightTest.kt
modules/tolk/testResources/org.ton.intellij.tolk/projects/chainlink-ton/contracts/contracts/lib/access/access_control.tolk

feat(tolk/tests): enable more inspections

---

modules/tolk/src/org/ton/intellij/tolk/psi/impl/TolkPrefixExpressionMixin.kt

fix(tolk/type-inference): fix `lazy ...` type inference

---

modules/tolk/src/org/ton/intellij/tolk/stub/TolkEnumStub.kt
modules/tolk/test/completion/TolkCompletionTest.kt

feat(tolk/completion): suggest enums as a type

---

modules/tolk/src/org/ton/intellij/tolk/ide/structure/TolkPsiStructureViewFactory.kt
modules/tolk/src/org/ton/intellij/tolk/psi/impl/TolkNamedElementImpl.kt

feat(tolk): show enums in the file structure view

---

modules/tolk/src/org/ton/intellij/tolk/ide/completion/TolkCompletionContributor.kt
modules/tolk/src/org/ton/intellij/tolk/ide/completion/TolkImportKeywordCompletionProvider.kt

fix(tolk/completion): don't show top level completion inside doc comments

---

modules/tolk/src/org/ton/intellij/tolk/doc/TolkDocumentationProvider.kt
modules/tolk/src/org/ton/intellij/tolk/ide/completion/TolkDotExpressionCompletionProvider.kt
modules/tolk/src/org/ton/intellij/tolk/ide/completion/TolkExpressionFieldProvider.kt
modules/tolk/src/org/ton/intellij/tolk/inspection/TolkStructInitializationInspection.kt
modules/tolk/src/org/ton/intellij/tolk/psi/impl/TolkStructFieldMixin.kt
modules/tolk/src/org/ton/intellij/tolk/psi/impl/TolkStructMixin.kt
modules/tolk/test/completion/TolkDotCompletionTest.kt
modules/tolk/test/completion/TolkStructInitCompletionTest.kt
modules/tolk/test/inspection/TolkStructInitializationInspectionTest.kt

feat(tolk/completion): don't add private fields to completion

---

modules/tolk/src/org/ton/intellij/tolk/psi/reference/TolkFieldLookupReference.kt
modules/tolk/src/org/ton/intellij/tolk/type/TolkTyAlias.kt
modules/tolk/test/completion/TolkDotCompletionTest.kt

fix(tolk/completion): fix method completion for aliases
